language: python
python:
- '3.7'
install:
- pip3 install -r requirements.txt
script:
- python -m unittest discover
deploy:
- provider: heroku
api_key:
secure: c0rXUz85VdwakwUc/zRcY/IGtmBTMoMZEmEwWXN7GdBgQZa+VG0IfQYVDH25/VtXmnkPF+lBMGXZzDAzlw311xCJ9rj7fYxzJ1wEU9Lpo6TyPpDWiNuK4DV+xeIpD5wwhZRpqY/p6ImAzo1n3ZuIpo5cmQX7YHr1Dm6GIRWpyexRhG1MnXpJPh7LZpbs3SWl1mZboJu1xmkKfOuQC6j/4T4FaRE6Z6pAAaURrBtQWuEhtGM3rF+WYWoitFtcIIWHtwpmUMLPQ1Gk7aRtyvvcLoGZLuQjgKbMwzh6YcdbVcxPufBOosnsUOkqIjsxrpANMA8Z6HHKPANFC3oIFbQ0+V62jIBNs6feDaRPjEpWPvmMIi4j7WB7xLXexkNSCayo/IPT5Lj//uSlJAv0cjsr4W8h/0uC8pGknIott+py4UT6QKYfDP8u4xCdVR4dNVbgdCABYIA6e0kEHe0DBaddeqIfyFySqPllToKLrebzBcBSR9rY6kmWTT7s7YZGPL3Xf3w71VeAH9nfKbgLKNxlxZJhPCz4QVVVx2Yx49ccLvzdVKGoIH9CZ+j1YAuMbYHil5ARlDKtsoLEkLgnDRvsGLmDWRv0/nq7ou3P9tQ9La3QDZ+E6k3KmzF0h5aoRzJS9TDSSuSwTQWv1FrS2phjArzu/NeGBG/9ma96neGEXy8=
app: hw3-webapp