language: python
python:
- '3.7'
install:
- pip3 install -r requirements.txt
script:
- python -m unittest discover
deploy:
  - provider: heroku
  api_key:
    secure: kGSSpXXLKB1pSEda5Ny59WhbuIGIu0O1AA9gZp+p25YsNfxHIJXVPKr4Zs7DHwmVitoc02ZLOov+A0greegnj0RQmyvxFudyuEXTFOinkuMlB4XGzerY6vgwmdEnlgk03SCaUimZHvuuo+p+qmI46GyzWX5rhprepcnNPU+axKjYYhiOUuBJa0sAkkCpkVn9sOzrRlfVh2QHfVWCS1+sAKVaVDlpTqhFTmL24iwyBGgNLXEkeKotyqDW8Y/BnOR+Lbo+eogkamq8GZMXIXPyls8wRmkpicT+lpfPCzw9YP6sW3vxfkdDqC0DscvGw2oYkf8ImXaKzGQZdaaUmcz8ACynfA5BsS9W+3qqH6OQyd1fgP+DNf8XbCOKsArC2Lg31rF12/WtJU8nPszdczNfIjX6jSLvBKDKONpF+S7hoFRLaeimek1ipj2AeO+LOmz66I2Gr7rURwv4PwyS+tdHPsILg9YtzgfjQ1hxxDm913B/YZRXW5qUbexoEUWUPat/WbJ3o2xmsYksXKLRHzkQX99gFUfbbaxwZKTj14hYt4o4D6IiXXTXioocrl7gfccj9Nq5gc1FsZBZboK4U/cKnSMffnY86W1GNHXGGXCGwDLgjcLOE4sMAmazuoTXhOJchwceg0cwgq2StgDEUajEeQchE3d2Br2vAPsvCbxmP/w=
  app: hw3-webapp